# Generated by Django 4.1.5 on 2023-01-16 12:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedEMail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('email', models.CharField(max_length=24, unique=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'InterestedEMail',
                'verbose_name_plural': 'InterestedEMails',
                'ordering': ('email',),
            },
        ),
    ]
