# Generated by Django 4.1.5 on 2023-01-16 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=254, verbose_name='Address')),
                ('number', models.CharField(max_length=254, verbose_name='Number')),
                ('city', models.CharField(max_length=32, verbose_name='city')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Zip Code')),
                ('more_info', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Additional Info')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ('city',),
                'managed': True,
            },
        ),
    ]
