# Generated by Django 4.1.5 on 2023-02-01 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_interestedemail_options_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Accessibility',
                'verbose_name_plural': 'Accessibility',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Bathroom',
                'verbose_name_plural': 'Bathrooms',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BookingSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=24, verbose_name='name')),
                ('site', models.URLField(max_length=254, verbose_name='site')),
            ],
            options={
                'verbose_name': 'Booking Site',
                'verbose_name_plural': 'Booking Sites',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Entertainment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Kitchen',
                'verbose_name_plural': 'Kitchens',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Essential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Essential',
                'verbose_name_plural': 'Essentials',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Family',
                'verbose_name_plural': 'Families',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Kitchen',
                'verbose_name_plural': 'Kitchens',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Laundry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Laundry',
                'verbose_name_plural': 'Laundries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Outside',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Outside',
                'verbose_name_plural': 'Outside',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Parking',
                'verbose_name_plural': 'Parking',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PoolSpa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=128, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Pool & Spa',
                'verbose_name_plural': 'Pool & Spa',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Safety',
                'verbose_name_plural': 'Safeties',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Space',
                'verbose_name_plural': 'Spaces',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('enabled', models.BooleanField(default=True)),
                ('ref', models.CharField(max_length=16, unique=True, verbose_name='Ref')),
                ('name', models.CharField(max_length=254, unique=True, verbose_name='Name')),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('virtual_tour', models.FileField(blank=True, default=None, null=True, upload_to='')),
                ('type', models.CharField(blank=True, choices=[('barn', 'Barn'), ('bed-and-breakfast', 'Bed and Breakfast'), ('boat', 'Boat'), ('bungalow', 'Bungalow'), ('bus', 'Bus'), ('cabin', 'Cabin'), ('camper', 'Camper'), ('caravan', 'Caravan'), ('casa-particulares', 'Casa Particulares'), ('castle', 'Castle'), ('cave', 'Cave'), ('chalet', 'Chalet'), ('condo', 'Condo'), ('cottage', 'Cottage'), ('country-house', 'Country House'), ('cycladic', 'Cycladic'), ('damusi', 'Damusi'), ('earth-home', 'Earth Home'), ('estate', 'Estate'), ('farm-house', 'Farm House'), ('guest-house', 'Guest House'), ('hanok', 'Hanok'), ('historic-home', 'Historic Home'), ('hotel', 'Hotel'), ('house', 'House'), ('houseboat', 'Houseboat'), ('lodge', 'Lodge'), ('minsus', 'Minsus'), ('resort', 'Resort'), ('riad', 'Riad'), ('ryokan', 'Ryokan'), ('shepherds-hut', "Shepherd's Hut"), ('specialty', 'Specialty'), ('studio', 'Studio'), ('tent', 'Tent'), ('tiny-home', 'Tiny Home'), ('tower', 'Tower'), ('townhouse', 'Townhouse'), ('train-car', 'Train Car'), ('treehouse', 'Treehouse'), ('trulli', 'Trulli'), ('villa', 'Villa'), ('windmill', 'Windmill'), ('yacht', 'Yacht'), ('yurt', 'Yurt')], default='', max_length=254, null=True, verbose_name='Type')),
                ('space', models.CharField(blank=True, choices=[('entire-house', 'Entire House'), ('private-room', 'Private Room'), ('casita-sep-guest-quarters', 'Casita/Sep Guest Quarters')], default='', max_length=254, null=True, verbose_name='Booked Space')),
                ('hosted_by', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Hosted By')),
                ('no_of_guest', models.IntegerField(verbose_name='No of Guest')),
                ('no_of_bedrooms', models.IntegerField(verbose_name='No of Bedrooms')),
                ('no_of_bathrooms', models.IntegerField(verbose_name='No of Bathrooms')),
                ('is_pet_allowed', models.BooleanField(default=True)),
                ('suitability', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
                ('host_note', models.TextField(blank=True, default='', null=True, verbose_name='Host Notes')),
                ('price_night', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ave $ Per Night')),
                ('email', models.CharField(blank=True, default='', max_length=128, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, default='', max_length=16, null=True, verbose_name='phone')),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('facebook', models.URLField(blank=True, default='', max_length=254, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, default='', max_length=254, null=True, verbose_name='Instagram')),
                ('tiktok', models.URLField(blank=True, default='', max_length=254, null=True, verbose_name='TikTok')),
                ('twitter', models.URLField(blank=True, default='', max_length=254, null=True, verbose_name='Twitter')),
                ('google_business', models.URLField(blank=True, default='', max_length=254, null=True, verbose_name='GoogleBusiness')),
                ('yelp', models.URLField(blank=True, default='', max_length=254, null=True, verbose_name='Yelp')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_address', to='core.address')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ('name',),
                'managed': True,
            },
        ),
    ]
